repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
    # Run the linter.
      - id: ruff
        args: ['check', '--select', 'I', '--exit-zero']

  # Mypy type checker
  - repo: local
    hooks:
      - id: mypy
        name: Analyze with Mypy
        entry: mypy --config-file mypy.ini
        language: python
        types: ['python']
        files: \.py$
        exclude: >-
          (?x)^(
            scripts/overtaking_analysis\.py|
            scripts/overtaking_experimental\.py|
            scripts/plot_rank_frame\.py|
            scripts/coordination_number_experimental\.py|
            src/plot_script\.py|
            src/plot_motivation\.py
          )$
        